 # here you need to know about job, like small description about it : job is kind of thing you need run once complete it should be terminated 
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  containers:
  - name: con1
    image: ubuntu

