apiVersion: v1
kind: pod
metadata:
  labels:
    app: liveness
    name: liveness-probe
spec:
  containers:
  - name: con1
    image: ubuntu
    args:
      - bin/sh
      - -c
      - touch /tmp/healthy; sleep 5000
    livenessprobe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 30

