apiVersion: v1
kind: Pod
metadata:
  name: mywebapp3
spec:
  containers:
  - name: con1
    image: ubuntu
    command: ["bin/bash", "-c", "while true; do echo hello vinay; sleep 5; done"]
  - name: container4
    image: httpd
    ports:
      - containerPort: 80
