apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 3
  selector:
    myname: vinay

  template:
    metadata:
      name: replica-pod
      labels:
        myname: vinay
    spec:
      containers:
      - name: web-cont
        image: nginx


